// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use crate::api::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1597117013;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__NoteDocument_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "NoteDocument_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::NoteDocument::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__RefinerySession_new_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RefinerySession_new",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::RefinerySession::new())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__RefinerySession_submit_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RefinerySession_submit",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>,
            >>::sse_decode(&mut deserializer);
            let api_input = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                        _ => unreachable!(),
                    }
                }
                let api_that_guard = api_that_guard.unwrap();
                let output_ok = Result::<_, ()>::Ok(crate::api::RefinerySession::submit(
                    &*api_that_guard,
                    api_input,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__RefinerySession_view_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RefinerySession_view",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                        _ => unreachable!(),
                    }
                }
                let api_that_guard = api_that_guard.unwrap();
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::RefinerySession::view(&*api_that_guard))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>
);
flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>
);

// Section: dart2rust

impl SseDecode for NoteDocument {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode for RefinerySession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::CommandOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_content = <String>::sse_decode(deserializer);
                return crate::api::CommandOutput::Print {
                    content: var_content,
                };
            }
            1 => {
                let mut var_target = <Vec<crate::api::FieldEntry>>::sse_decode(deserializer);
                return crate::api::CommandOutput::ViewItems { target: var_target };
            }
            2 => {
                let mut var_changeHistory =
                    <Vec<crate::api::VersionEntry>>::sse_decode(deserializer);
                let mut var_target = <Vec<crate::api::DiffEntry>>::sse_decode(deserializer);
                return crate::api::CommandOutput::DiffView {
                    change_history: var_changeHistory,
                    target: var_target,
                };
            }
            3 => {
                let mut var_versions = <Vec<crate::api::VersionEntry>>::sse_decode(deserializer);
                return crate::api::CommandOutput::VersionSummaries {
                    versions: var_versions,
                };
            }
            4 => {
                let mut var_path = <Option<String>>::sse_decode(deserializer);
                let mut var_version = <Option<i64>>::sse_decode(deserializer);
                return crate::api::CommandOutput::Reverted {
                    path: var_path,
                    version: var_version,
                };
            }
            5 => {
                return crate::api::CommandOutput::RevertErrorNoHistory;
            }
            6 => {
                return crate::api::CommandOutput::DiffErrorNoHistory;
            }
            7 => {
                return crate::api::CommandOutput::InvalidVersion;
            }
            8 => {
                let mut var_fields = <Vec<crate::api::FieldEntry>>::sse_decode(deserializer);
                return crate::api::CommandOutput::ApprovedDocument { fields: var_fields };
            }
            9 => {
                return crate::api::CommandOutput::NoOutput;
            }
            10 => {
                return crate::api::CommandOutput::EditComplete;
            }
            11 => {
                return crate::api::CommandOutput::AddComplete;
            }
            12 => {
                return crate::api::CommandOutput::RemoveComplete;
            }
            13 => {
                let mut var_column = <String>::sse_decode(deserializer);
                return crate::api::CommandOutput::ColumnPrompt { column: var_column };
            }
            14 => {
                return crate::api::CommandOutput::AddCancelled;
            }
            15 => {
                return crate::api::CommandOutput::GeneralMode;
            }
            16 => {
                let mut var_locked = <Vec<String>>::sse_decode(deserializer);
                return crate::api::CommandOutput::GlobalMode { locked: var_locked };
            }
            17 => {
                let mut var_targeted = <Vec<String>>::sse_decode(deserializer);
                let mut var_unknown = <Vec<String>>::sse_decode(deserializer);
                let mut var_locked = <Vec<String>>::sse_decode(deserializer);
                return crate::api::CommandOutput::TargetedFields {
                    targeted: var_targeted,
                    unknown: var_unknown,
                    locked: var_locked,
                };
            }
            18 => {
                return crate::api::CommandOutput::Locked;
            }
            19 => {
                return crate::api::CommandOutput::Unlocked;
            }
            20 => {
                let mut var_changed = <Vec<crate::api::FieldEntry>>::sse_decode(deserializer);
                return crate::api::CommandOutput::Pending {
                    changed: var_changed,
                };
            }
            21 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::CommandOutput::AiServerError {
                    message: var_message,
                };
            }
            22 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::CommandOutput::ImageGenerationSuccess { path: var_path };
            }
            23 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::CommandOutput::ImageGenerationError {
                    message: var_message,
                };
            }
            24 => {
                return crate::api::CommandOutput::UploadSuccess;
            }
            25 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::CommandOutput::UploadError {
                    message: var_message,
                };
            }
            26 => {
                let mut var_filenames = <Vec<String>>::sse_decode(deserializer);
                return crate::api::CommandOutput::UploadedFiles {
                    filenames: var_filenames,
                };
            }
            27 => {
                return crate::api::CommandOutput::VersionCommitted;
            }
            28 => {
                return crate::api::CommandOutput::NoPendingDoc;
            }
            29 => {
                return crate::api::CommandOutput::UnknownField;
            }
            30 => {
                return crate::api::CommandOutput::ElementLocked;
            }
            31 => {
                return crate::api::CommandOutput::UnknownCommand;
            }
            32 => {
                let mut var_fields = <Vec<crate::api::FieldEntry>>::sse_decode(deserializer);
                return crate::api::CommandOutput::InvalidArgument { fields: var_fields };
            }
            33 => {
                return crate::api::CommandOutput::Unsupported;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::DiffEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_old = <crate::api::DiffSide>::sse_decode(deserializer);
        let mut var_new_ = <crate::api::DiffSide>::sse_decode(deserializer);
        return crate::api::DiffEntry {
            path: var_path,
            old: var_old,
            new: var_new_,
        };
    }
}

impl SseDecode for crate::api::DiffSide {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_version = <i64>::sse_decode(deserializer);
        return crate::api::DiffSide {
            content: var_content,
            version: var_version,
        };
    }
}

impl SseDecode for crate::api::FieldEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        return crate::api::FieldEntry {
            path: var_path,
            value: var_value,
        };
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::DiffEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::DiffEntry>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FieldEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FieldEntry>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::VersionEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::VersionEntry>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for crate::api::VersionEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_number = <i64>::sse_decode(deserializer);
        let mut var_summary = <String>::sse_decode(deserializer);
        return crate::api::VersionEntry {
            number: var_number,
            summary: var_summary,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__NoteDocument_default_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__RefinerySession_new_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__RefinerySession_submit_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__RefinerySession_view_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<NoteDocument> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<NoteDocument> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<NoteDocument>> for NoteDocument {
    fn into_into_dart(self) -> FrbWrapper<NoteDocument> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<RefinerySession> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<RefinerySession> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<RefinerySession>> for RefinerySession {
    fn into_into_dart(self) -> FrbWrapper<RefinerySession> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::CommandOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::CommandOutput::Print { content } => {
                [0.into_dart(), content.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::ViewItems { target } => {
                [1.into_dart(), target.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::DiffView {
                change_history,
                target,
            } => [
                2.into_dart(),
                change_history.into_into_dart().into_dart(),
                target.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::CommandOutput::VersionSummaries { versions } => {
                [3.into_dart(), versions.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::Reverted { path, version } => [
                4.into_dart(),
                path.into_into_dart().into_dart(),
                version.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::CommandOutput::RevertErrorNoHistory => [5.into_dart()].into_dart(),
            crate::api::CommandOutput::DiffErrorNoHistory => [6.into_dart()].into_dart(),
            crate::api::CommandOutput::InvalidVersion => [7.into_dart()].into_dart(),
            crate::api::CommandOutput::ApprovedDocument { fields } => {
                [8.into_dart(), fields.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::NoOutput => [9.into_dart()].into_dart(),
            crate::api::CommandOutput::EditComplete => [10.into_dart()].into_dart(),
            crate::api::CommandOutput::AddComplete => [11.into_dart()].into_dart(),
            crate::api::CommandOutput::RemoveComplete => [12.into_dart()].into_dart(),
            crate::api::CommandOutput::ColumnPrompt { column } => {
                [13.into_dart(), column.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::AddCancelled => [14.into_dart()].into_dart(),
            crate::api::CommandOutput::GeneralMode => [15.into_dart()].into_dart(),
            crate::api::CommandOutput::GlobalMode { locked } => {
                [16.into_dart(), locked.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::TargetedFields {
                targeted,
                unknown,
                locked,
            } => [
                17.into_dart(),
                targeted.into_into_dart().into_dart(),
                unknown.into_into_dart().into_dart(),
                locked.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::CommandOutput::Locked => [18.into_dart()].into_dart(),
            crate::api::CommandOutput::Unlocked => [19.into_dart()].into_dart(),
            crate::api::CommandOutput::Pending { changed } => {
                [20.into_dart(), changed.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::AiServerError { message } => {
                [21.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::ImageGenerationSuccess { path } => {
                [22.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::ImageGenerationError { message } => {
                [23.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::UploadSuccess => [24.into_dart()].into_dart(),
            crate::api::CommandOutput::UploadError { message } => {
                [25.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::UploadedFiles { filenames } => {
                [26.into_dart(), filenames.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::VersionCommitted => [27.into_dart()].into_dart(),
            crate::api::CommandOutput::NoPendingDoc => [28.into_dart()].into_dart(),
            crate::api::CommandOutput::UnknownField => [29.into_dart()].into_dart(),
            crate::api::CommandOutput::ElementLocked => [30.into_dart()].into_dart(),
            crate::api::CommandOutput::UnknownCommand => [31.into_dart()].into_dart(),
            crate::api::CommandOutput::InvalidArgument { fields } => {
                [32.into_dart(), fields.into_into_dart().into_dart()].into_dart()
            }
            crate::api::CommandOutput::Unsupported => [33.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::CommandOutput {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::CommandOutput> for crate::api::CommandOutput {
    fn into_into_dart(self) -> crate::api::CommandOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DiffEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.old.into_into_dart().into_dart(),
            self.new.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DiffEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DiffEntry> for crate::api::DiffEntry {
    fn into_into_dart(self) -> crate::api::DiffEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DiffSide {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.content.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DiffSide {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DiffSide> for crate::api::DiffSide {
    fn into_into_dart(self) -> crate::api::DiffSide {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FieldEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FieldEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FieldEntry> for crate::api::FieldEntry {
    fn into_into_dart(self) -> crate::api::FieldEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::VersionEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.number.into_into_dart().into_dart(),
            self.summary.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::VersionEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::VersionEntry> for crate::api::VersionEntry {
    fn into_into_dart(self) -> crate::api::VersionEntry {
        self
    }
}

impl SseEncode for NoteDocument {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode for RefinerySession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::CommandOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::CommandOutput::Print { content } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(content, serializer);
            }
            crate::api::CommandOutput::ViewItems { target } => {
                <i32>::sse_encode(1, serializer);
                <Vec<crate::api::FieldEntry>>::sse_encode(target, serializer);
            }
            crate::api::CommandOutput::DiffView {
                change_history,
                target,
            } => {
                <i32>::sse_encode(2, serializer);
                <Vec<crate::api::VersionEntry>>::sse_encode(change_history, serializer);
                <Vec<crate::api::DiffEntry>>::sse_encode(target, serializer);
            }
            crate::api::CommandOutput::VersionSummaries { versions } => {
                <i32>::sse_encode(3, serializer);
                <Vec<crate::api::VersionEntry>>::sse_encode(versions, serializer);
            }
            crate::api::CommandOutput::Reverted { path, version } => {
                <i32>::sse_encode(4, serializer);
                <Option<String>>::sse_encode(path, serializer);
                <Option<i64>>::sse_encode(version, serializer);
            }
            crate::api::CommandOutput::RevertErrorNoHistory => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::CommandOutput::DiffErrorNoHistory => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::CommandOutput::InvalidVersion => {
                <i32>::sse_encode(7, serializer);
            }
            crate::api::CommandOutput::ApprovedDocument { fields } => {
                <i32>::sse_encode(8, serializer);
                <Vec<crate::api::FieldEntry>>::sse_encode(fields, serializer);
            }
            crate::api::CommandOutput::NoOutput => {
                <i32>::sse_encode(9, serializer);
            }
            crate::api::CommandOutput::EditComplete => {
                <i32>::sse_encode(10, serializer);
            }
            crate::api::CommandOutput::AddComplete => {
                <i32>::sse_encode(11, serializer);
            }
            crate::api::CommandOutput::RemoveComplete => {
                <i32>::sse_encode(12, serializer);
            }
            crate::api::CommandOutput::ColumnPrompt { column } => {
                <i32>::sse_encode(13, serializer);
                <String>::sse_encode(column, serializer);
            }
            crate::api::CommandOutput::AddCancelled => {
                <i32>::sse_encode(14, serializer);
            }
            crate::api::CommandOutput::GeneralMode => {
                <i32>::sse_encode(15, serializer);
            }
            crate::api::CommandOutput::GlobalMode { locked } => {
                <i32>::sse_encode(16, serializer);
                <Vec<String>>::sse_encode(locked, serializer);
            }
            crate::api::CommandOutput::TargetedFields {
                targeted,
                unknown,
                locked,
            } => {
                <i32>::sse_encode(17, serializer);
                <Vec<String>>::sse_encode(targeted, serializer);
                <Vec<String>>::sse_encode(unknown, serializer);
                <Vec<String>>::sse_encode(locked, serializer);
            }
            crate::api::CommandOutput::Locked => {
                <i32>::sse_encode(18, serializer);
            }
            crate::api::CommandOutput::Unlocked => {
                <i32>::sse_encode(19, serializer);
            }
            crate::api::CommandOutput::Pending { changed } => {
                <i32>::sse_encode(20, serializer);
                <Vec<crate::api::FieldEntry>>::sse_encode(changed, serializer);
            }
            crate::api::CommandOutput::AiServerError { message } => {
                <i32>::sse_encode(21, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::CommandOutput::ImageGenerationSuccess { path } => {
                <i32>::sse_encode(22, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::CommandOutput::ImageGenerationError { message } => {
                <i32>::sse_encode(23, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::CommandOutput::UploadSuccess => {
                <i32>::sse_encode(24, serializer);
            }
            crate::api::CommandOutput::UploadError { message } => {
                <i32>::sse_encode(25, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::CommandOutput::UploadedFiles { filenames } => {
                <i32>::sse_encode(26, serializer);
                <Vec<String>>::sse_encode(filenames, serializer);
            }
            crate::api::CommandOutput::VersionCommitted => {
                <i32>::sse_encode(27, serializer);
            }
            crate::api::CommandOutput::NoPendingDoc => {
                <i32>::sse_encode(28, serializer);
            }
            crate::api::CommandOutput::UnknownField => {
                <i32>::sse_encode(29, serializer);
            }
            crate::api::CommandOutput::ElementLocked => {
                <i32>::sse_encode(30, serializer);
            }
            crate::api::CommandOutput::UnknownCommand => {
                <i32>::sse_encode(31, serializer);
            }
            crate::api::CommandOutput::InvalidArgument { fields } => {
                <i32>::sse_encode(32, serializer);
                <Vec<crate::api::FieldEntry>>::sse_encode(fields, serializer);
            }
            crate::api::CommandOutput::Unsupported => {
                <i32>::sse_encode(33, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::DiffEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <crate::api::DiffSide>::sse_encode(self.old, serializer);
        <crate::api::DiffSide>::sse_encode(self.new, serializer);
    }
}

impl SseEncode for crate::api::DiffSide {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.content, serializer);
        <i64>::sse_encode(self.version, serializer);
    }
}

impl SseEncode for crate::api::FieldEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::DiffEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::DiffEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FieldEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FieldEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::VersionEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::VersionEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for crate::api::VersionEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.number, serializer);
        <String>::sse_encode(self.summary, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::api::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_information_refinery_ffi_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_information_refinery_ffi_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>::decrement_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_information_refinery_ffi_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_information_refinery_ffi_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::api::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>::decrement_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
