// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_output`, `document_fields`, `map_to_entries`, `render_value`, `set_to_sorted_vec`, `version_map_to_entries`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_map`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `generated_images_mut`, `generated_images`, `get_field`, `schema`, `set_field`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteDocument>>
abstract class NoteDocument implements RustOpaqueInterface {
  static Future<NoteDocument> default_() =>
      RustLib.instance.api.crateApiNoteDocumentDefault();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RefinerySession>>
abstract class RefinerySession implements RustOpaqueInterface {
  factory RefinerySession() =>
      RustLib.instance.api.crateApiRefinerySessionNew();

  /// Runs one turn of the local editing pipeline (`parse_input` -> `apply`,
  /// bypassing `resolve_side_effect`). Free text and the AI/image/upload/
  /// accept/reject/exit commands return [`CommandOutput::Unsupported`].
  CommandOutput submit({required String input});

  /// The current document, rendered field-by-field.
  CommandOutput view();
}

@freezed
sealed class CommandOutput with _$CommandOutput {
  const CommandOutput._();

  const factory CommandOutput.print({required String content}) =
      CommandOutput_Print;
  const factory CommandOutput.viewItems({required List<FieldEntry> target}) =
      CommandOutput_ViewItems;
  const factory CommandOutput.diffView({
    required List<VersionEntry> changeHistory,
    required List<DiffEntry> target,
  }) = CommandOutput_DiffView;
  const factory CommandOutput.versionSummaries({
    required List<VersionEntry> versions,
  }) = CommandOutput_VersionSummaries;
  const factory CommandOutput.reverted({String? path, PlatformInt64? version}) =
      CommandOutput_Reverted;
  const factory CommandOutput.revertErrorNoHistory() =
      CommandOutput_RevertErrorNoHistory;
  const factory CommandOutput.diffErrorNoHistory() =
      CommandOutput_DiffErrorNoHistory;
  const factory CommandOutput.invalidVersion() = CommandOutput_InvalidVersion;
  const factory CommandOutput.approvedDocument({
    required List<FieldEntry> fields,
  }) = CommandOutput_ApprovedDocument;
  const factory CommandOutput.noOutput() = CommandOutput_NoOutput;
  const factory CommandOutput.editComplete() = CommandOutput_EditComplete;
  const factory CommandOutput.addComplete() = CommandOutput_AddComplete;
  const factory CommandOutput.removeComplete() = CommandOutput_RemoveComplete;
  const factory CommandOutput.columnPrompt({required String column}) =
      CommandOutput_ColumnPrompt;
  const factory CommandOutput.addCancelled() = CommandOutput_AddCancelled;
  const factory CommandOutput.generalMode() = CommandOutput_GeneralMode;
  const factory CommandOutput.globalMode({required List<String> locked}) =
      CommandOutput_GlobalMode;
  const factory CommandOutput.targetedFields({
    required List<String> targeted,
    required List<String> unknown,
    required List<String> locked,
  }) = CommandOutput_TargetedFields;
  const factory CommandOutput.locked() = CommandOutput_Locked;
  const factory CommandOutput.unlocked() = CommandOutput_Unlocked;
  const factory CommandOutput.pending({required List<FieldEntry> changed}) =
      CommandOutput_Pending;
  const factory CommandOutput.aiServerError({required String message}) =
      CommandOutput_AiServerError;
  const factory CommandOutput.imageGenerationSuccess({required String path}) =
      CommandOutput_ImageGenerationSuccess;
  const factory CommandOutput.imageGenerationError({required String message}) =
      CommandOutput_ImageGenerationError;
  const factory CommandOutput.uploadSuccess() = CommandOutput_UploadSuccess;
  const factory CommandOutput.uploadError({required String message}) =
      CommandOutput_UploadError;
  const factory CommandOutput.uploadedFiles({required List<String> filenames}) =
      CommandOutput_UploadedFiles;
  const factory CommandOutput.versionCommitted() =
      CommandOutput_VersionCommitted;
  const factory CommandOutput.noPendingDoc() = CommandOutput_NoPendingDoc;
  const factory CommandOutput.unknownField() = CommandOutput_UnknownField;
  const factory CommandOutput.elementLocked() = CommandOutput_ElementLocked;
  const factory CommandOutput.unknownCommand() = CommandOutput_UnknownCommand;
  const factory CommandOutput.invalidArgument({
    required List<FieldEntry> fields,
  }) = CommandOutput_InvalidArgument;

  /// No AI session / image generator / upload backend is wired in yet.
  const factory CommandOutput.unsupported() = CommandOutput_Unsupported;
}

/// A single path's before/after in a `/diff`.
class DiffEntry {
  final String path;
  final DiffSide old;
  final DiffSide new_;

  const DiffEntry({required this.path, required this.old, required this.new_});

  @override
  int get hashCode => path.hashCode ^ old.hashCode ^ new_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          old == other.old &&
          new_ == other.new_;
}

/// One side of a `/diff`.
class DiffSide {
  final String content;
  final PlatformInt64 version;

  const DiffSide({required this.content, required this.version});

  @override
  int get hashCode => content.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffSide &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          version == other.version;
}

/// A rendered `path -> value` pair (a document field, a `/view` target, a
/// `/diff` field, …).
class FieldEntry {
  final String path;
  final String value;

  const FieldEntry({required this.path, required this.value});

  @override
  int get hashCode => path.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          value == other.value;
}

/// A `/history` or `/diff` version entry.
class VersionEntry {
  final PlatformInt64 number;
  final String summary;

  const VersionEntry({required this.number, required this.summary});

  @override
  int get hashCode => number.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionEntry &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          summary == other.summary;
}
