// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1597117013;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'information_refinery_ffi',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<NoteDocument> crateApiNoteDocumentDefault();

  RefinerySession crateApiRefinerySessionNew();

  CommandOutput crateApiRefinerySessionSubmit({
    required RefinerySession that,
    required String input,
  });

  CommandOutput crateApiRefinerySessionView({required RefinerySession that});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NoteDocument;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NoteDocument;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_NoteDocumentPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RefinerySession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RefinerySession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RefinerySessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<NoteDocument> crateApiNoteDocumentDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNoteDocumentDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNoteDocumentDefaultConstMeta =>
      const TaskConstMeta(debugName: "NoteDocument_default", argNames: []);

  @override
  RefinerySession crateApiRefinerySessionNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRefinerySessionNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRefinerySessionNewConstMeta =>
      const TaskConstMeta(debugName: "RefinerySession_new", argNames: []);

  @override
  CommandOutput crateApiRefinerySessionSubmit({
    required RefinerySession that,
    required String input,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
            that,
            serializer,
          );
          sse_encode_String(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_command_output,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRefinerySessionSubmitConstMeta,
        argValues: [that, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRefinerySessionSubmitConstMeta =>
      const TaskConstMeta(
        debugName: "RefinerySession_submit",
        argNames: ["that", "input"],
      );

  @override
  CommandOutput crateApiRefinerySessionView({required RefinerySession that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_command_output,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRefinerySessionViewConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRefinerySessionViewConstMeta =>
      const TaskConstMeta(
        debugName: "RefinerySession_view",
        argNames: ["that"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NoteDocument => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NoteDocument => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RefinerySession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RefinerySession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession;

  @protected
  NoteDocument
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoteDocumentImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RefinerySession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RefinerySessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RefinerySession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RefinerySessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NoteDocument
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoteDocumentImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RefinerySession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RefinerySessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  CommandOutput dco_decode_command_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CommandOutput_Print(content: dco_decode_String(raw[1]));
      case 1:
        return CommandOutput_ViewItems(
          target: dco_decode_list_field_entry(raw[1]),
        );
      case 2:
        return CommandOutput_DiffView(
          changeHistory: dco_decode_list_version_entry(raw[1]),
          target: dco_decode_list_diff_entry(raw[2]),
        );
      case 3:
        return CommandOutput_VersionSummaries(
          versions: dco_decode_list_version_entry(raw[1]),
        );
      case 4:
        return CommandOutput_Reverted(
          path: dco_decode_opt_String(raw[1]),
          version: dco_decode_opt_box_autoadd_i_64(raw[2]),
        );
      case 5:
        return CommandOutput_RevertErrorNoHistory();
      case 6:
        return CommandOutput_DiffErrorNoHistory();
      case 7:
        return CommandOutput_InvalidVersion();
      case 8:
        return CommandOutput_ApprovedDocument(
          fields: dco_decode_list_field_entry(raw[1]),
        );
      case 9:
        return CommandOutput_NoOutput();
      case 10:
        return CommandOutput_EditComplete();
      case 11:
        return CommandOutput_AddComplete();
      case 12:
        return CommandOutput_RemoveComplete();
      case 13:
        return CommandOutput_ColumnPrompt(column: dco_decode_String(raw[1]));
      case 14:
        return CommandOutput_AddCancelled();
      case 15:
        return CommandOutput_GeneralMode();
      case 16:
        return CommandOutput_GlobalMode(locked: dco_decode_list_String(raw[1]));
      case 17:
        return CommandOutput_TargetedFields(
          targeted: dco_decode_list_String(raw[1]),
          unknown: dco_decode_list_String(raw[2]),
          locked: dco_decode_list_String(raw[3]),
        );
      case 18:
        return CommandOutput_Locked();
      case 19:
        return CommandOutput_Unlocked();
      case 20:
        return CommandOutput_Pending(
          changed: dco_decode_list_field_entry(raw[1]),
        );
      case 21:
        return CommandOutput_AiServerError(message: dco_decode_String(raw[1]));
      case 22:
        return CommandOutput_ImageGenerationSuccess(
          path: dco_decode_String(raw[1]),
        );
      case 23:
        return CommandOutput_ImageGenerationError(
          message: dco_decode_String(raw[1]),
        );
      case 24:
        return CommandOutput_UploadSuccess();
      case 25:
        return CommandOutput_UploadError(message: dco_decode_String(raw[1]));
      case 26:
        return CommandOutput_UploadedFiles(
          filenames: dco_decode_list_String(raw[1]),
        );
      case 27:
        return CommandOutput_VersionCommitted();
      case 28:
        return CommandOutput_NoPendingDoc();
      case 29:
        return CommandOutput_UnknownField();
      case 30:
        return CommandOutput_ElementLocked();
      case 31:
        return CommandOutput_UnknownCommand();
      case 32:
        return CommandOutput_InvalidArgument(
          fields: dco_decode_list_field_entry(raw[1]),
        );
      case 33:
        return CommandOutput_Unsupported();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DiffEntry dco_decode_diff_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DiffEntry(
      path: dco_decode_String(arr[0]),
      old: dco_decode_diff_side(arr[1]),
      new_: dco_decode_diff_side(arr[2]),
    );
  }

  @protected
  DiffSide dco_decode_diff_side(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DiffSide(
      content: dco_decode_String(arr[0]),
      version: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  FieldEntry dco_decode_field_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FieldEntry(
      path: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DiffEntry> dco_decode_list_diff_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_diff_entry).toList();
  }

  @protected
  List<FieldEntry> dco_decode_list_field_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_field_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VersionEntry> dco_decode_list_version_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_version_entry).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VersionEntry dco_decode_version_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VersionEntry(
      number: dco_decode_i_64(arr[0]),
      summary: dco_decode_String(arr[1]),
    );
  }

  @protected
  NoteDocument
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NoteDocumentImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RefinerySession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RefinerySessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RefinerySession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RefinerySessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NoteDocument
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NoteDocumentImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RefinerySession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RefinerySessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  CommandOutput sse_decode_command_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_content = sse_decode_String(deserializer);
        return CommandOutput_Print(content: var_content);
      case 1:
        var var_target = sse_decode_list_field_entry(deserializer);
        return CommandOutput_ViewItems(target: var_target);
      case 2:
        var var_changeHistory = sse_decode_list_version_entry(deserializer);
        var var_target = sse_decode_list_diff_entry(deserializer);
        return CommandOutput_DiffView(
          changeHistory: var_changeHistory,
          target: var_target,
        );
      case 3:
        var var_versions = sse_decode_list_version_entry(deserializer);
        return CommandOutput_VersionSummaries(versions: var_versions);
      case 4:
        var var_path = sse_decode_opt_String(deserializer);
        var var_version = sse_decode_opt_box_autoadd_i_64(deserializer);
        return CommandOutput_Reverted(path: var_path, version: var_version);
      case 5:
        return CommandOutput_RevertErrorNoHistory();
      case 6:
        return CommandOutput_DiffErrorNoHistory();
      case 7:
        return CommandOutput_InvalidVersion();
      case 8:
        var var_fields = sse_decode_list_field_entry(deserializer);
        return CommandOutput_ApprovedDocument(fields: var_fields);
      case 9:
        return CommandOutput_NoOutput();
      case 10:
        return CommandOutput_EditComplete();
      case 11:
        return CommandOutput_AddComplete();
      case 12:
        return CommandOutput_RemoveComplete();
      case 13:
        var var_column = sse_decode_String(deserializer);
        return CommandOutput_ColumnPrompt(column: var_column);
      case 14:
        return CommandOutput_AddCancelled();
      case 15:
        return CommandOutput_GeneralMode();
      case 16:
        var var_locked = sse_decode_list_String(deserializer);
        return CommandOutput_GlobalMode(locked: var_locked);
      case 17:
        var var_targeted = sse_decode_list_String(deserializer);
        var var_unknown = sse_decode_list_String(deserializer);
        var var_locked = sse_decode_list_String(deserializer);
        return CommandOutput_TargetedFields(
          targeted: var_targeted,
          unknown: var_unknown,
          locked: var_locked,
        );
      case 18:
        return CommandOutput_Locked();
      case 19:
        return CommandOutput_Unlocked();
      case 20:
        var var_changed = sse_decode_list_field_entry(deserializer);
        return CommandOutput_Pending(changed: var_changed);
      case 21:
        var var_message = sse_decode_String(deserializer);
        return CommandOutput_AiServerError(message: var_message);
      case 22:
        var var_path = sse_decode_String(deserializer);
        return CommandOutput_ImageGenerationSuccess(path: var_path);
      case 23:
        var var_message = sse_decode_String(deserializer);
        return CommandOutput_ImageGenerationError(message: var_message);
      case 24:
        return CommandOutput_UploadSuccess();
      case 25:
        var var_message = sse_decode_String(deserializer);
        return CommandOutput_UploadError(message: var_message);
      case 26:
        var var_filenames = sse_decode_list_String(deserializer);
        return CommandOutput_UploadedFiles(filenames: var_filenames);
      case 27:
        return CommandOutput_VersionCommitted();
      case 28:
        return CommandOutput_NoPendingDoc();
      case 29:
        return CommandOutput_UnknownField();
      case 30:
        return CommandOutput_ElementLocked();
      case 31:
        return CommandOutput_UnknownCommand();
      case 32:
        var var_fields = sse_decode_list_field_entry(deserializer);
        return CommandOutput_InvalidArgument(fields: var_fields);
      case 33:
        return CommandOutput_Unsupported();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DiffEntry sse_decode_diff_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_old = sse_decode_diff_side(deserializer);
    var var_new_ = sse_decode_diff_side(deserializer);
    return DiffEntry(path: var_path, old: var_old, new_: var_new_);
  }

  @protected
  DiffSide sse_decode_diff_side(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_content = sse_decode_String(deserializer);
    var var_version = sse_decode_i_64(deserializer);
    return DiffSide(content: var_content, version: var_version);
  }

  @protected
  FieldEntry sse_decode_field_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return FieldEntry(path: var_path, value: var_value);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiffEntry> sse_decode_list_diff_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiffEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_diff_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<FieldEntry> sse_decode_list_field_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FieldEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_field_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VersionEntry> sse_decode_list_version_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VersionEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_version_entry(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VersionEntry sse_decode_version_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_number = sse_decode_i_64(deserializer);
    var var_summary = sse_decode_String(deserializer);
    return VersionEntry(number: var_number, summary: var_summary);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
    NoteDocument self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NoteDocumentImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    RefinerySession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RefinerySessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    RefinerySession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RefinerySessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteDocument(
    NoteDocument self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NoteDocumentImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRefinerySession(
    RefinerySession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RefinerySessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_command_output(CommandOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CommandOutput_Print(content: final content):
        sse_encode_i_32(0, serializer);
        sse_encode_String(content, serializer);
      case CommandOutput_ViewItems(target: final target):
        sse_encode_i_32(1, serializer);
        sse_encode_list_field_entry(target, serializer);
      case CommandOutput_DiffView(
        changeHistory: final changeHistory,
        target: final target,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_list_version_entry(changeHistory, serializer);
        sse_encode_list_diff_entry(target, serializer);
      case CommandOutput_VersionSummaries(versions: final versions):
        sse_encode_i_32(3, serializer);
        sse_encode_list_version_entry(versions, serializer);
      case CommandOutput_Reverted(path: final path, version: final version):
        sse_encode_i_32(4, serializer);
        sse_encode_opt_String(path, serializer);
        sse_encode_opt_box_autoadd_i_64(version, serializer);
      case CommandOutput_RevertErrorNoHistory():
        sse_encode_i_32(5, serializer);
      case CommandOutput_DiffErrorNoHistory():
        sse_encode_i_32(6, serializer);
      case CommandOutput_InvalidVersion():
        sse_encode_i_32(7, serializer);
      case CommandOutput_ApprovedDocument(fields: final fields):
        sse_encode_i_32(8, serializer);
        sse_encode_list_field_entry(fields, serializer);
      case CommandOutput_NoOutput():
        sse_encode_i_32(9, serializer);
      case CommandOutput_EditComplete():
        sse_encode_i_32(10, serializer);
      case CommandOutput_AddComplete():
        sse_encode_i_32(11, serializer);
      case CommandOutput_RemoveComplete():
        sse_encode_i_32(12, serializer);
      case CommandOutput_ColumnPrompt(column: final column):
        sse_encode_i_32(13, serializer);
        sse_encode_String(column, serializer);
      case CommandOutput_AddCancelled():
        sse_encode_i_32(14, serializer);
      case CommandOutput_GeneralMode():
        sse_encode_i_32(15, serializer);
      case CommandOutput_GlobalMode(locked: final locked):
        sse_encode_i_32(16, serializer);
        sse_encode_list_String(locked, serializer);
      case CommandOutput_TargetedFields(
        targeted: final targeted,
        unknown: final unknown,
        locked: final locked,
      ):
        sse_encode_i_32(17, serializer);
        sse_encode_list_String(targeted, serializer);
        sse_encode_list_String(unknown, serializer);
        sse_encode_list_String(locked, serializer);
      case CommandOutput_Locked():
        sse_encode_i_32(18, serializer);
      case CommandOutput_Unlocked():
        sse_encode_i_32(19, serializer);
      case CommandOutput_Pending(changed: final changed):
        sse_encode_i_32(20, serializer);
        sse_encode_list_field_entry(changed, serializer);
      case CommandOutput_AiServerError(message: final message):
        sse_encode_i_32(21, serializer);
        sse_encode_String(message, serializer);
      case CommandOutput_ImageGenerationSuccess(path: final path):
        sse_encode_i_32(22, serializer);
        sse_encode_String(path, serializer);
      case CommandOutput_ImageGenerationError(message: final message):
        sse_encode_i_32(23, serializer);
        sse_encode_String(message, serializer);
      case CommandOutput_UploadSuccess():
        sse_encode_i_32(24, serializer);
      case CommandOutput_UploadError(message: final message):
        sse_encode_i_32(25, serializer);
        sse_encode_String(message, serializer);
      case CommandOutput_UploadedFiles(filenames: final filenames):
        sse_encode_i_32(26, serializer);
        sse_encode_list_String(filenames, serializer);
      case CommandOutput_VersionCommitted():
        sse_encode_i_32(27, serializer);
      case CommandOutput_NoPendingDoc():
        sse_encode_i_32(28, serializer);
      case CommandOutput_UnknownField():
        sse_encode_i_32(29, serializer);
      case CommandOutput_ElementLocked():
        sse_encode_i_32(30, serializer);
      case CommandOutput_UnknownCommand():
        sse_encode_i_32(31, serializer);
      case CommandOutput_InvalidArgument(fields: final fields):
        sse_encode_i_32(32, serializer);
        sse_encode_list_field_entry(fields, serializer);
      case CommandOutput_Unsupported():
        sse_encode_i_32(33, serializer);
    }
  }

  @protected
  void sse_encode_diff_entry(DiffEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_diff_side(self.old, serializer);
    sse_encode_diff_side(self.new_, serializer);
  }

  @protected
  void sse_encode_diff_side(DiffSide self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.content, serializer);
    sse_encode_i_64(self.version, serializer);
  }

  @protected
  void sse_encode_field_entry(FieldEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_diff_entry(
    List<DiffEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_diff_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_field_entry(
    List<FieldEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_field_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_version_entry(
    List<VersionEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_version_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_version_entry(VersionEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.number, serializer);
    sse_encode_String(self.summary, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class NoteDocumentImpl extends RustOpaque implements NoteDocument {
  // Not to be used by end users
  NoteDocumentImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NoteDocumentImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NoteDocument,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NoteDocument,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NoteDocumentPtr,
  );
}

@sealed
class RefinerySessionImpl extends RustOpaque implements RefinerySession {
  // Not to be used by end users
  RefinerySessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RefinerySessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RefinerySession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RefinerySession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RefinerySessionPtr,
  );

  /// Runs one turn of the local editing pipeline (`parse_input` -> `apply`,
  /// bypassing `resolve_side_effect`). Free text and the AI/image/upload/
  /// accept/reject/exit commands return [`CommandOutput::Unsupported`].
  CommandOutput submit({required String input}) => RustLib.instance.api
      .crateApiRefinerySessionSubmit(that: this, input: input);

  /// The current document, rendered field-by-field.
  CommandOutput view() =>
      RustLib.instance.api.crateApiRefinerySessionView(that: this);
}
